apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-project3-be-user-application
  labels:
    app: udacity-project3-be-user-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-project3-be-user-application
  template:
    metadata:
      labels:
        app: udacity-project3-be-user-application
    spec:
      containers:
      - name: udagram-api-user
        image: tinhdh/udagram-api-user:v1.0.0
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: sec-env-udacity-project3-application
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sec-env-udacity-project3-application
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: sec-env-udacity-project3-application
              key: POSTGRES_DB
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: sec-env-udacity-project3-application
              key: JWT_SECRET
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: conf-env-udacity-project3-application
              key:  POSTGRES_HOST
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: sec-aws-udacity-project3-application
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: sec-aws-udacity-project3-application
              key: AWS_PROFILE
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: conf-env-udacity-project3-application
              key:  AWS_BUCKET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: conf-env-udacity-project3-application
              key:  URL
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: sec-aws-udacity-project3-application
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: sec-aws-udacity-project3-application
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
              secretKeyRef:
                name: sec-aws-udacity-project3-application
                key: AWS_DEFAULT_REGION
        ports:
        - containerPort: 8080